In [27]:
from torch import nn
import torch
import numpy as np
import random 

class LinearNet(nn.Module):
    def __init__(self, hidden_size=2):
        super().__init__()
        self.last_layer = nn.Linear(2, 2)
        self.rll = nn.ReLU()
        self.classifier = nn.Linear(2, 2)
        
    def forward(self, x):
        x = self.last_layer(x)
        x = self.rll(x)
        x = self.classifier(x)
        return x    

In [32]:
input =torch.tensor([0.0,1.0])
label = torch.tensor(1)

torch.manual_seed(0)
np.random.seed(0)
random.seed(0)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)
model = LinearNet()
for n,m in model.named_modules():
    m.register_forward_hook(lambda m,i,o: print(o))

model.classifier.register_full_backward_pre_hook(lambda m,o: print(m,o))
def break_graph(module, grad_output):
    return None
model.classifier.register_full_backward_pre_hook(break_graph,prepend=True)
model.classifier.register_full_backward_hook(lambda m,i,o: print(m,i,o))

model.last_layer.register_full_backward_hook(lambda m,i,o: print(m,i,o))

criterion = nn.CrossEntropyLoss()


logits = model(input)
# print(logits)
loss = criterion(logits, label)
loss.backward()
# print(loss)

tensor([ 0.1070, -0.3308], grad_fn=<ViewBackward0>)
tensor([0.1070, 0.0000], grad_fn=<ReluBackward0>)
tensor([-0.2152, -0.1457], grad_fn=<ViewBackward0>)
tensor([-0.2152, -0.1457], grad_fn=<BackwardHookFunctionBackward>)
Linear(in_features=2, out_features=2, bias=True) (tensor([ 0.4826, -0.4826]),)
Linear(in_features=2, out_features=2, bias=True) (tensor([0.0235, 0.1803]),) (tensor([ 0.4826, -0.4826]),)


In [4]:
for n,_ in model.named_parameters():
    print(n)


last_layer.weight
last_layer.bias
classifier.weight
classifier.bias


In [32]:
lambda m,i,o: print(o)

<function __main__.<lambda>(m, i, o)>